name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  # First job to set the variable
  set-var:
    runs-on: ubuntu-latest

    outputs:
      MY_VAR: ${{ steps.set_var_step.outputs.my_var }}

    steps:
      - name: Set a variable
        id: set_var_step
        run: echo "my_var=Hello from set-var job!" >> $GITHUB_OUTPUT

  # Second job to print the variable set by the first job
  print-var:
    runs-on: ubuntu-latest
    needs: set-var

    steps:
      - name: Print the variable from set-var job
        run: echo "The value of MY_VAR is: ${{ needs.set-var.outputs.my_var }}"
        
